spring.data.mongodb.uri=mongodb+srv://chathuabeyrathne2001:U8J1GGRLxS7QpPVj@gamer.n7tbt.mongodb.net/?retryWrites=true&w=majority&appName=Gamer
spring.data.mongodb.database: gamer_db

spring.mail.host=smtp.gmail.com
spring.mail.port=587
spring.mail.username=chathurya.abeyrathna@aiesec.net
spring.mail.password=duxj xwws mksx ldai
spring.mail.properties.mail.smtp.auth=true
spring.mail.properties.mail.smtp.starttls.enable=true

# This line bypasses certificate validation
spring.mail.properties.mail.smtp.ssl.trust=*






